baseURL = "https://lamzy.net/"
languageCode = "zh-Hants-TW"
title = "Lamzy 懶誌"
theme = "PaperMod"
paginate = 15
enableInlineShortcodes = true
enableRobotsTXT = true
hasCJKLanguage = true
isCJKLanguage = true
enableEmoji = true
defaultContentLanguage = 'zh-tw'
summaryLength = 100
googleAnalytics = 'G-58BLPMJTXE'

[minify]
disableXML = true

[outputs]
home = [ "HTML", "RSS", "JSON" ]

[permalinks]
posts = "/:slug/"

[params]
env = "production"
description = "紀錄使用python和php等多種程式處理醫院藥庫的日常工作情形。"
keyword = [
  "python",
  "php",
  "hospital",
  "pharmacy",
  "stock",
  "inventory",
  "pharmacist",
  "醫院",
  "藥庫",
  "藥師",
  "藥學部",
  "藥劑",
  "庫存管理",
  "請購",
  "庫管",
  "安全量",
  "基準量"
]
author = "lambo"
defaultTheme = "light"
disableThemeToggle = true
dateFormat = "2006/1/2"
ShowReadingTime = true
ShowWordCount = true
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = true
#label.icon = "/favicon.svg"

[params.assets]
disableHLJS = true
#favicon = "/favicon.svg"
#favicon16x16 = "/favicon.svg"
#favicon32x32 = "/favicon.svg"
#apple_touch_icon = "/favicon.svg"
#safari_pinned_tab = "/favicon.svg"

[params.homeInfoParams]
Title = "Lamzy 懶誌"
Content = """
Hi, I'm Lambo, a pharmacist at a hospital in Taiwan.{{< i class="twicon-main-island" >}}

Here's my work log from warehouse business, with the tasks involving coding and data analysis.

嗨，我是 Lambo ，台灣某間醫院的藥庫藥師。

這裡面是一些為了工作需求而自學的程式紀錄，以 Python 和 PHP 為主。
"""


[[params.socialIcons]]
name = "facebook"
url = "https://www.facebook.com/lambo.lyu/"

[[params.socialIcons]]
name = "instagram"
url = "https://www.instagram.com/lambolyu/"

[[params.socialIcons]]
name = "email"
url = "mailto:lambolyu@gmail.com"

pygmentsUseClasses = true

[markup]
[markup.goldmark]
[markup.goldmark.extensions]
definitionList = true
footnote = true
linkify = true
linkifyProtocol = 'https'
strikethrough = true
table = true
taskList = true
[markup.goldmark.extensions.cjk]
eastAsianLineBreaks = false
enable = false
escapedSpace = false
[markup.goldmark.extensions.typographer]
apostrophe = '&rsquo;'
disable = false
ellipsis = '&hellip;'
emDash = '&mdash;'
enDash = '&ndash;'
leftAngleQuote = '&laquo;'
leftDoubleQuote = '&ldquo;'
leftSingleQuote = '&lsquo;'
rightAngleQuote = '&raquo;'
rightDoubleQuote = '&rdquo;'
rightSingleQuote = '&rsquo;'
[markup.goldmark.parser]
autoHeadingID = true
autoHeadingIDType = 'github'
wrapStandAloneImageWithinParagraph = true
[markup.goldmark.parser.attribute]
block = false
title = true
[markup.goldmark.renderer]
hardWraps = false
unsafe = false
xhtml = false
[markup.highlight]
#noClasses = false
codeFences = true
guessSyntax = true
lineNos = false
style = 'monokai'

[[menu.main]]
identifier = "archives"
name = "所有文章"
url = "/archives/"
weight = 10

#[[menu.main]]
#identifier = "tags"
#name = "標籤"
#url = "/tags/"
#weight = 30

[[menu.main]]
identifier = "categories"
name = "文章分類"
url = "/categories/"
weight = 40

[[menu.main]]
identifier = "home"
name = "首頁"
url = "/"
weight = 0

[sitemap]
changeFreq = "daily"
filename = "sitemap.xml"
priority = -1