baseURL = "https://lambolyu.netlify.app/"
languageCode = "zh-Hants-TW"
title = "Lambo’s Work Log"
theme = "PaperMod"
paginate = 15
enableInlineShortcodes = true
enableRobotsTXT = true
hasCJKLanguage = true
isCJKLanguage = true
enableEmoji = true
defaultContentLanguage = 'zh-tw'
googleAnalytics = 'G-58BLPMJTXE'

[minify]
disableXML = true

[outputs]
home = [ "HTML", "RSS", "JSON" ]

[permalinks]
posts = "/:year/:month/:slug/"

[params]
env = "production"
description = "紀錄使用python和php等多種程式處理醫院藥庫的日常工作情形。"
keyword = [
  "python",
  "php",
  "hospital",
  "pharmacy",
  "stock",
  "inventory",
  "pharmacist",
  "醫院",
  "藥庫",
  "藥師",
  "藥學部",
  "藥劑",
  "庫存管理",
  "請購",
  "庫管",
  "安全量",
  "基準量"
]
author = "lambo"
defaultTheme = "light"
disableThemeToggle = true
dateFormat = "2006/1/2"
ShowReadingTime = true
ShowWordCount = true
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = true
#label.icon = "/favicon.svg"

[params.assets]
disableHLJS = true
#favicon = "/favicon.svg"
#favicon16x16 = "/favicon.svg"
#favicon32x32 = "/favicon.svg"
#apple_touch_icon = "/favicon.svg"
#safari_pinned_tab = "/favicon.svg"

[params.homeInfoParams]
Title = "Lambo's Work Log"
Content = """
某醫院藥庫日常工作的程式紀錄

很多的 Python 加上一點點麵條式 PHP

完全不管程式效率和邏輯，可以用就好的自學者 (？)
"""

[[params.socialIcons]]
name = "facebook"
url = "https://www.facebook.com/lambo.lyu/"

[[params.socialIcons]]
name = "instagram"
url = "https://www.instagram.com/lambolyu/"

[[params.socialIcons]]
name = "email"
url = "mailto:lambolyu@gmail.com"

pygmentsUseClasses = true

[markup.highlight]
#noClasses = false
codeFences = true
guessSyntax = true
lineNos = false
style = "monokai"

[[menu.main]]
identifier = "archives"
name = "文章列表"
url = "/archives/"
weight = 10

[[menu.main]]
identifier = "tags"
name = "標籤"
url = "/tags/"
weight = 30

[[menu.main]]
identifier = "categories"
name = "分類"
url = "/categories/"
weight = 40

[[menu.main]]
identifier = "home"
name = "首頁"
url = "/"
weight = 0

[sitemap]
changeFreq = "daily"
filename = "sitemap.xml"
priority = -1